// Generated by Framer (eda58b2)
export default function metadata(params, activeLocale) {
  return {
    breakpoints: [
      { hash: "15wd91v", mediaQuery: "(min-width: 1600px)" },
      {
        hash: "pwiwsw",
        mediaQuery: "(min-width: 1400px) and (max-width: 1599.98px)",
      },
      {
        hash: "72rtr7",
        mediaQuery: "(min-width: 1200px) and (max-width: 1399.98px)",
      },
      { hash: "1een5sr", mediaQuery: "(max-width: 1199.98px)" },
    ],
    description: "THE CHIBI INU",
    elements: {},
    framerSearch: { index: false },
    robots: "noindex",
    serializationId: "framer-URP33",
    socialImage:
      "../framerusercontent.com/assets/1svKQkvbhaVSDk9CwNNJWUL7T8.png",
    title: "RYOTARO",
    viewport: "width=device-width",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
