// Generated by Framer (8b16de8)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getLoadingLazyAtYPosition,
  Image as Image1,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
  withOptimizedAppearEffect,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const Image1WithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
  withFX(Image1)
);
const cycleOrder = ["r0taiegi6", "yc7a1bs_j", "XxXIZQeFO"];
const serializationHash = "framer-Xd8Gi";
const variantClassNames = {
  r0taiegi6: "framer-v-130t7dz",
  XxXIZQeFO: "framer-v-2lgxaq",
  yc7a1bs_j: "framer-v-8vzolc",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transition2 = {
  damping: 12,
  delay: 0,
  mass: 1,
  stiffness: 97,
  type: "spring",
};
const animation = {
  opacity: 1,
  rotate: -2,
  rotateX: 0,
  rotateY: 0,
  scale: 0.9,
  skewX: 0,
  skewY: 0,
  transition: transition2,
};
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const transition3 = {
  damping: 23,
  delay: 0,
  mass: 1,
  stiffness: 400,
  type: "spring",
};
const animation1 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition3,
  x: 0,
  y: 0,
};
const animation2 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 630,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Variant 1": "r0taiegi6",
  "Variant 2": "yc7a1bs_j",
  "Variant 3": "XxXIZQeFO",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "r0taiegi6",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "r0taiegi6",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTapad14a6 = activeVariantCallback(async (...args) => {
    setVariant("yc7a1bs_j");
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (baseVariant === "yc7a1bs_j") return false;
    return true;
  };
  const isDisplayed1 = () => {
    if (baseVariant === "yc7a1bs_j") return true;
    return false;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-130t7dz",
            className,
            classNames
          ),
          "data-border": true,
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "r0taiegi6",
          ref: refBinding,
          style: {
            "--border-bottom-width": "1px",
            "--border-color": "rgb(193, 139, 58)",
            "--border-left-width": "1px",
            "--border-right-width": "1px",
            "--border-style": "solid",
            "--border-top-width": "1px",
            background:
              "linear-gradient(254deg, rgba(194, 140, 58, 0.15) 0%, rgba(194, 140, 58, 0) 31%, rgba(227, 194, 145, 0.34) 57.99999999999999%, rgba(194, 140, 58, 0) 74.85395551801803%, rgba(194, 140, 58, 0.24) 100%)",
            borderBottomLeftRadius: 34,
            borderBottomRightRadius: 34,
            borderTopLeftRadius: 34,
            borderTopRightRadius: 34,
            ...style,
          },
          ...addPropertyOverrides(
            {
              XxXIZQeFO: { "data-framer-name": "Variant 3" },
              yc7a1bs_j: { "data-framer-name": "Variant 2" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            isDisplayed() &&
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-tgm9v9",
                layoutDependency: layoutDependency,
                layoutId: "NXtr5YwMd",
                children: [
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        dir: "auto",
                        style: {
                          "--font-selector": "R0Y7V2lua3kgUm91Z2gtNTAw",
                          "--framer-font-family":
                            '"Winky Rough", "Winky Rough Placeholder", sans-serif',
                          "--framer-font-size": "64px",
                          "--framer-font-weight": "500",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(17, 20, 23))",
                        },
                        children: "WATCH THE CHART",
                      }),
                    }),
                    className: "framer-3ljumu",
                    fonts: ["GF;Winky Rough-500"],
                    layoutDependency: layoutDependency,
                    layoutId: "CM9Sw0DDo",
                    style: {
                      "--extracted-r6o4lv": "rgb(17, 20, 23)",
                      "--framer-link-text-color": "rgb(0, 153, 255)",
                      "--framer-link-text-decoration": "underline",
                    },
                    variants: {
                      XxXIZQeFO: { "--extracted-2gxw0f": "rgb(17, 20, 23)" },
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        XxXIZQeFO: {
                          children: /*#__PURE__*/ _jsxs(React.Fragment, {
                            children: [
                              /*#__PURE__*/ _jsx(motion.p, {
                                dir: "auto",
                                style: {
                                  "--font-selector": "R0Y7V2lua3kgUm91Z2gtNTAw",
                                  "--framer-font-family":
                                    '"Winky Rough", "Winky Rough Placeholder", sans-serif',
                                  "--framer-font-size": "49px",
                                  "--framer-font-weight": "500",
                                  "--framer-text-alignment": "center",
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, rgb(17, 20, 23))",
                                },
                                children: "WATCH ",
                              }),
                              /*#__PURE__*/ _jsx(motion.p, {
                                dir: "auto",
                                style: {
                                  "--font-selector": "R0Y7V2lua3kgUm91Z2gtNTAw",
                                  "--framer-font-family":
                                    '"Winky Rough", "Winky Rough Placeholder", sans-serif',
                                  "--framer-font-size": "49px",
                                  "--framer-font-weight": "500",
                                  "--framer-text-alignment": "center",
                                  "--framer-text-color":
                                    "var(--extracted-2gxw0f, rgb(17, 20, 23))",
                                },
                                children: "THE CHART",
                              }),
                            ],
                          }),
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                  /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-11auje",
                    "data-highlight": true,
                    layoutDependency: layoutDependency,
                    layoutId: "mlLqfn__e",
                    onTap: onTapad14a6,
                    style: {
                      backgroundColor: "rgb(193, 139, 58)",
                      borderBottomLeftRadius: 16,
                      borderBottomRightRadius: 16,
                      borderTopLeftRadius: 16,
                      borderTopRightRadius: 16,
                    },
                    whileHover: animation,
                    children: /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          dir: "auto",
                          style: {
                            "--font-selector": "R0Y7V2lua3kgUm91Z2gtNTAw",
                            "--framer-font-family":
                              '"Winky Rough", "Winky Rough Placeholder", sans-serif',
                            "--framer-font-size": "19px",
                            "--framer-font-weight": "500",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, rgb(236, 238, 241))",
                          },
                          children: "CLICK HERE",
                        }),
                      }),
                      className: "framer-12wjtdb",
                      fonts: ["GF;Winky Rough-500"],
                      layoutDependency: layoutDependency,
                      layoutId: "ziIqqdxZt",
                      style: {
                        "--extracted-r6o4lv": "rgb(236, 238, 241)",
                        "--framer-link-text-color": "rgb(0, 153, 255)",
                        "--framer-link-text-decoration": "underline",
                      },
                      verticalAlignment: "center",
                      withExternalLayout: true,
                    }),
                  }),
                ],
              }),
            isDisplayed1() &&
              /*#__PURE__*/ _jsx(Image1WithFXWithOptimizedAppearEffect, {
                __perspectiveFX: false,
                __smartComponentFX: true,
                __targetOpacity: 1,
                animate: animation1,
                background: {
                  alt: "",
                  fit: "fill",
                  intrinsicHeight: 1024,
                  intrinsicWidth: 468,
                  pixelHeight: 2048,
                  pixelWidth: 936,
                  src: "../framerusercontent.com/images/ecBO3Jkig1vFxVhToi4xX4b3hqI.png?width=936&height=2048",
                  srcSet:
                    "../framerusercontent.com/images/ecBO3Jkig1vFxVhToi4xX4b3hqI.png?width=936&height=2048 936w",
                },
                className: "framer-h9zabn",
                "data-framer-appear-id": "h9zabn",
                "data-framer-name": "10",
                initial: animation2,
                layoutDependency: layoutDependency,
                layoutId: "fO7lUjPUr",
                optimized: true,
                transformTemplate: transformTemplate1,
                ...addPropertyOverrides(
                  {
                    yc7a1bs_j: {
                      background: {
                        alt: "",
                        fit: "fill",
                        intrinsicHeight: 1024,
                        intrinsicWidth: 468,
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) +
                            (componentViewport?.height || 722.5) -
                            583.5
                        ),
                        pixelHeight: 2048,
                        pixelWidth: 936,
                        sizes: "295px",
                        src: "../framerusercontent.com/images/ecBO3Jkig1vFxVhToi4xX4b3hqI.png?width=936&height=2048",
                        srcSet:
                          "../framerusercontent.com/images/ecBO3Jkig1vFxVhToi4xX4b3hqI.png?width=936&height=2048 936w",
                      },
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
              }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-Xd8Gi.framer-4lhlxl, .framer-Xd8Gi .framer-4lhlxl { display: block; }",
  ".framer-Xd8Gi.framer-130t7dz { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: 723px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 55px 24px 55px 24px; position: relative; width: 920px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-Xd8Gi .framer-tgm9v9 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 139px 0px 139px 0px; position: relative; width: 1px; }",
  ".framer-Xd8Gi .framer-3ljumu, .framer-Xd8Gi .framer-12wjtdb { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-Xd8Gi .framer-11auje { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 5px 22px 5px 22px; position: relative; width: min-content; will-change: var(--framer-will-change-effect-override, transform); }",
  ".framer-Xd8Gi .framer-h9zabn { aspect-ratio: 0.45703125 / 1; bottom: -62px; flex: none; height: var(--framer-aspect-ratio-supported, 646px); left: 50%; overflow: visible; position: absolute; width: 295px; z-index: 1; }",
  ".framer-Xd8Gi.framer-v-2lgxaq.framer-130t7dz { width: 390px; }",
  '.framer-Xd8Gi[data-border="true"]::after, .framer-Xd8Gi [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 722.5
 * @framerIntrinsicWidth 920
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"yc7a1bs_j":{"layout":["fixed","fixed"]},"XxXIZQeFO":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerGWiVGCi_d = withCSS(Component, css, "framer-Xd8Gi");
export default FramerGWiVGCi_d;
FramerGWiVGCi_d.displayName = "chart";
FramerGWiVGCi_d.defaultProps = { height: 722.5, width: 920 };
addPropertyControls(FramerGWiVGCi_d, {
  variant: {
    options: ["r0taiegi6", "yc7a1bs_j", "XxXIZQeFO"],
    optionTitles: ["Variant 1", "Variant 2", "Variant 3"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  FramerGWiVGCi_d,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Winky Rough",
          source: "google",
          style: "normal",
          uiFamilyName: "Winky Rough",
          url: "https://fonts.gstatic.com/s/winkyrough/v4/t5tzIRwIMoSXA0WSPBjQxJzjxc0_NyCBbx8bVSVuMrJB-KCmzg.woff2",
          weight: "500",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerGWiVGCi_d",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerAutoSizeImages: "true",
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "722.5",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"yc7a1bs_j":{"layout":["fixed","fixed"]},"XxXIZQeFO":{"layout":["fixed","fixed"]}}}',
        framerComponentViewportWidth: "true",
        framerColorSyntax: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicWidth: "920",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./GWiVGCi_d.map
