// Generated by Framer (8b16de8)
export default function metadata(params, activeLocale) {
  return {
    description: "THE CHIBI INU",
    favicon:
      "./framerusercontent.com/assets/xcbESmZwpluQok1gQdLxU3ytx54.png",
    robots: "max-image-preview:large",
    socialImage:
      "./framerusercontent.com/assets/1svKQkvbhaVSDk9CwNNJWUL7T8.png",
    title: "RYOTARO",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
