// Generated by Framer (eda58b2)
import siteMetadata from "#framer/local/siteMetadata/siteMetadata/siteMetadata.js";
export default function metadata(params, activeLocale) {
  return {
    breakpoints: [
      { hash: "b8d5f9", mediaQuery: "(min-width: 1600px)" },
      {
        hash: "zi9ntf",
        mediaQuery: "(min-width: 1400px) and (max-width: 1599.98px)",
      },
      {
        hash: "9vne4t",
        mediaQuery: "(min-width: 1200px) and (max-width: 1399.98px)",
      },
      { hash: "1dqqod6", mediaQuery: "(max-width: 1199.98px)" },
    ],
    description: siteMetadata(params, activeLocale).description,
    elements: {},
    robots: "max-image-preview:large",
    serializationId: "framer-ddVCB",
    title: siteMetadata(params, activeLocale).title || "Pfpmaker",
    viewport: "width=device-width",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
