// Generated by Framer (6ca5d98)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addPropertyControls,
  ControlType,
  cx,
  motion,
  useSVGTemplate,
  withCSS,
} from "framer";
import * as React from "react";
import { forwardRef } from "react";
const mask = "var(--framer-icon-mask)";
const Base = /*#__PURE__*/ forwardRef(function (props, ref) {
  return /*#__PURE__*/ _jsx("svg", {
    ...props,
    ref: ref,
    children: props.children,
  });
});
const MotionSVG = motion.create(Base);
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
  const { animated, layoutId, children, ...rest } = props;
  return animated
    ? /*#__PURE__*/ _jsx(MotionSVG, {
        ...rest,
        layoutId: layoutId,
        ref: ref,
        children: children,
      })
    : /*#__PURE__*/ _jsx("svg", { ...rest, ref: ref, children: children });
});
const svg =
  '<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 12.75 7.313 C 14.279 8.413 16.116 9.004 18 9 L 18 5.25 C 15.101 5.25 12.75 2.899 12.75 0 L 9 0 L 9 12.375 C 8.999 13.675 8.047 14.78 6.76 14.97 C 5.474 15.161 4.242 14.382 3.863 13.137 C 3.485 11.893 4.075 10.56 5.25 10.002 L 5.25 6 C 2.266 6.532 0 9.238 0 12.375 C 0 15.896 2.854 18.75 6.375 18.75 C 9.896 18.75 12.75 15.896 12.75 12.375 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="18.75px" id="XxjC59UQP" transform="translate(3 2.25)" width="18px"/><path d="M 12.75 7.313 C 14.279 8.413 16.116 9.004 18 9 L 18 5.25 C 15.101 5.25 12.75 2.899 12.75 0 L 9 0 L 9 12.375 C 8.999 13.675 8.047 14.78 6.76 14.97 C 5.474 15.161 4.242 14.382 3.863 13.137 C 3.485 11.893 4.075 10.56 5.25 10.002 L 5.25 6 C 2.266 6.532 0 9.238 0 12.375 C 0 15.896 2.854 18.75 6.375 18.75 C 9.896 18.75 12.75 15.896 12.75 12.375 Z" fill="transparent" height="18.75px" id="J5_aSIe85" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(3 2.25)" width="18px"/></svg>';
const getProps = ({ alpha, color, height, id, width, width1, ...props }) => {
  return {
    ...props,
    ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
    lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
    qxTvv_EBh: alpha ?? props.qxTvv_EBh,
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const {
    style,
    className,
    layoutId,
    variant,
    ezTt3ayMo,
    lschgej4H,
    qxTvv_EBh,
    ...restProps
  } = getProps(props);
  const href = useSVGTemplate("4153440109", svg);
  return /*#__PURE__*/ _jsx(SVG, {
    ...restProps,
    className: cx("framer-wQsp6", className),
    layoutId: layoutId,
    ref: ref,
    role: "presentation",
    style: {
      "--1m6trwb": qxTvv_EBh,
      "--21h8s6": ezTt3ayMo,
      "--pgex8v": lschgej4H,
      ...style,
    },
    viewBox: "0 0 24 24",
    children: /*#__PURE__*/ _jsx("use", { href: href }),
  });
});
const css = [
  `.framer-wQsp6 { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"ezTt3ayMo":"color","lschgej4H":"width1","qxTvv_EBh":"alpha"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Tiktok Logo","color":{"type":"variable","value":"21h8s6"},"set":{"localId":"vectorSet/NGVKdicsm","id":"NGVKdicsm","moduleId":"omX0gWFPqDwhaiWwf6ab"}}
 * @framerDisableUnlink true
 */ const Icon = withCSS(Component, css, "framer-wQsp6");
Icon.displayName = "Tiktok Logo";
export default Icon;
addPropertyControls(Icon, {
  ezTt3ayMo: {
    defaultValue: "rgb(0, 0, 0)",
    hidden: false,
    title: "Color",
    type: ControlType.Color,
  },
  lschgej4H: {
    defaultValue: 1.5,
    displayStepper: true,
    hidden: false,
    max: 6,
    min: 0,
    step: 0.5,
    title: "Width",
    type: ControlType.Number,
  },
  qxTvv_EBh: {
    defaultValue: 0,
    displayStepper: true,
    hidden: false,
    max: 1,
    min: 0,
    step: 0.1,
    title: "Alpha",
    type: ControlType.Number,
  },
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Icon",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerIntrinsicHeight: "24",
        framerDisableUnlink: "true",
        framerVariables:
          '{"ezTt3ayMo":"color","lschgej4H":"width1","qxTvv_EBh":"alpha"}',
        framerSupportedLayoutHeight: "any-prefer-fixed",
        framerIntrinsicWidth: "24",
        framerSupportedLayoutWidth: "any-prefer-fixed",
        framerImmutableVariables: "true",
        framerVector:
          '{"name":"Tiktok Logo","color":{"type":"variable","value":"21h8s6"},"set":{"localId":"vectorSet/NGVKdicsm","id":"NGVKdicsm","moduleId":"omX0gWFPqDwhaiWwf6ab"}}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
